### ISSUE TITLE
百度云盘后继有人了

### ISSUE THREAD

**Issue by lijjOrz** [komeiji-satori/Dress#101]

**Comment by Easte-r** [comment]
are you ok？

**Comment by Mouse0w0** [comment]
没用的，项目不允许超过一定的大小，Understand？

**Comment by cnwangjie** [comment]
Collaborators of the repository can delete issues currently.

**Comment by kagurazakayashi** [comment]
这个项目中的内容，可不是能像度盘那样随便就能上传任意内容的。
以及非常不鼓励将度盘拿来比，它们是完全不同的产品。
此项目的照片质量、尺度、版权、大小、数量都有审核，不要将此网站和此项目视为度盘。
