### ISSUE TITLE
来个青见 亻子回复一下我👋👋👋

### ISSUE THREAD

**Issue by hrzzz** [komeiji-satori/Dress#1052]
## 我就是想测试一下issues怎么用
#1051 
#1049 
# 发现能用markdown
🐱‍🚀🐱‍👓🐱‍💻🐱‍🐉😊😂🤣😍👌🤷‍♂️🎉🐱‍👤🎂🤳
❤🧡💛💚💙💜🤎🖤💖💓💞❣💔🤍
有点意思
还能@别人呢，cool😎
@komeiji-satori 
@akechisatori
![wallhaven-r7lgpw](https://user-images.githubusercontent.com/37526239/116532044-6988a380-a912-11eb-9663-b24089b6fc5d.png)

**Comment by hrzzz** [comment]
发现一个小问题，只有contributor才能新建label

**Comment by lzhbhlrPython** [comment]
az（（（

**Comment by Thomasvader** [comment]
很好玩哈哈！！！

**Comment by Wei-Jian-Xian** [comment]
#1080 嘿嘿嘿
