### ISSUE TITLE
仓库体积已经好大了，clone一次要好久，要不要归档下历史commit？

### ISSUE THREAD

**Issue by Nigh** [komeiji-satori/Dress#106]
clone一次要花好久好久欸...历史commit可以归档下吧？

**Comment by wizardforcel** [comment]
可以 sparse checkout

**Comment by Nigh** [comment]
没有用过这个功能。
这样是不是还是会把目录下的历史全部Clone下来呢？
那样拉取下来的还能正常push么？

Get Outlook for Android<https://aka.ms/ghei36>

**Comment by rekols** [comment]
please close this issues, now.
