### ISSUE TITLE
问下啊,这个仓库现在废弃了吗(Ask, is this warehouse abandoned now?)

### ISSUE THREAD

**Issue by mis1042** [komeiji-satori/Dress#1061]
如题,已经有很多Pull Requests没处理,仓库废弃了吗?
There are many pull requests that have not been processed. Is the warehouse abandoned?

**Comment by jshensh** [comment]
没有时间。。

**Comment by undefined-moe** [comment]
可以考虑 [WorldDriven](https://www.worlddriven.org/) 系统（？

**Comment by mis1042** [comment]
这

**Comment by mis1042** [comment]
> 可以考虑 [WorldDriven](https://www.worlddriven.org/) 系统（？

What is that ?那是什么

**Comment by xtexChooser** [comment]
> > 可以考虑 [WorldDriven](https://www.worlddriven.org/) 系统（？
> 
> What is that ?那是什么

直接用GithubActions全部合并23333

**Comment by jshensh** [comment]
> > > 可以考虑 [WorldDriven](https://www.worlddriven.org/) 系统（？
> > 
> > 
> > What is that ?那是什么
> 
> 直接用GithubActions全部合并23333

还是要审一下的

**Comment by mis1042** [comment]
> > > > 可以考虑 [WorldDriven](https://www.worlddriven.org/) 系统（？
> > > 
> > > 
> > > What is that ?那是什么
> > 
> > 
> > 直接用GithubActions全部合并23333
> 
> 还是要审一下的

那就多招几个信得过的管理/bushi

**Comment by YogurtZebra** [comment]
能用AI审核吗（想屁

**Comment by xtexChooser** [comment]
谁提出谁实现

--xtex

发件人: Yogurt Zebra
发送时间: 2021年7月28日 20:48
收件人: komeiji-satori/Dress
抄送: xtex; Comment
主题: Re: [komeiji-satori/Dress] 问下啊,这个仓库现在废弃了吗(Ask, is this warehouse abandoned now?) (#1061)

能用AI审核吗（想屁

**Comment by jshensh** [comment]
> 能用AI审核吗（想屁

https://github.com/komeiji-satori/Dress/pull/1074 看看这个,能给过么

**Comment by YogurtZebra** [comment]
> > 能用AI审核吗（想屁
> 
> https://github.com/komeiji-satori/Dress/pull/1074 看看这个,能给过么

草
那还是只能找管理员了

**Comment by huamurui** [comment]
......好像成反面教材了

**Comment by BBleae** [comment]
咕了
