### ISSUE TITLE
这是不对的，应该...

### ISSUE THREAD

**Issue by hye** [komeiji-satori/Dress#109]
直接套个好看的模板 弄个gh-pages web   方便大家欣赏呀😂 
（或者直接hugo这一类 能生成静态）
大佬们传图，和一个固定格式的json / yaml  （包括头图，bio， social, 安利？)

推荐这个主题 https://html5up.net/ethereal

**Comment by rekols** [comment]
please close this issues. now.

**Comment by hye** [comment]
> please close this issues. now.

Are you one of contributors? Are you the repo owner? Please do tell me why...

**Comment by rekols** [comment]
> > please close this issues. now.
> 
> Are you one of contributors? Are you the repo owner? Please do tell me why...

yes, i am.

**Comment by ly0** [comment]
@rekols 忽然发现我们来自同一个城市。。

**Comment by rekols** [comment]
@ly0 老乡吗

**Comment by hye** [comment]
> > > please close this issues. now.
> > 
> > 
> > Are you one of contributors? Are you the repo owner? Please do tell me why...
> 
> yes, i am.

To @komeiji-satori ： 4L 这人欺诈吧，https://github.com/komeiji-satori/Dress/graphs/contributors contributors 没有他，owner就更不用说了 不知道是真傻还是装傻
