### ISSUE TITLE
这可耻的star量 | the shameful star count 😉

### ISSUE THREAD

**Issue by youyinnn** [komeiji-satori/Dress#110]
我一点都不心动

------

I don't want to join them at all (I'm serious) 😉

**Comment by ouyangpeng** [comment]
真的有点搞！

**Comment by DarkSherlock** [comment]
还有181个fork

**Comment by showtan001** [comment]
还有20个issue

**Comment by bolee** [comment]
2133 star!!!

**Comment by youyinnn** [comment]
2,732 star!!!

**Comment by studentmain** [comment]
感觉你们要上trend

**Comment by akechisatori** [comment]
> 感觉你们要上trend

![image](https://user-images.githubusercontent.com/43605695/51448755-b5c40100-1d63-11e9-95de-db8f6da2dc68.png)

**Comment by kagurazakayashi** [comment]
trend……太……太刺激了

**Comment by thautwarm** [comment]
3天1000。这还不上trend?

**Comment by Mouse0w0** [comment]
厉害了我的哥

**Comment by Surile** [comment]
已经上热搜了

**Comment by plqin-xiaohao** [comment]
我的推荐一整天都是它

**Comment by ARXChrono** [comment]
> 
> 
> 我一点都不心动
> 
> I don't want to join them at all (I'm serious) 😉

Very educational, Learn git and wear skirts. Its the moment you've been waiting for. 😉

**Comment by yukiexe** [comment]
導流 -> #82
