### ISSUE TITLE
建议重构使用webp的图片格式上传

### ISSUE THREAD

**Issue by zhangyiming748** [komeiji-satori/Dress#1129]
我想贡献代码首先要下载分支和git历史记录，git历史记录里应该有大量的冗余数据，我已经克隆了1G数据了，居然才55%，要不发起项目的人清空一下提交历史吧

**Comment by zhangyiming748** [comment]
我已经尝试了仅下载第一层
```shell
git config --global core.compression 0
git clone --depth 1 git@github.com:komeiji-satori/Dress.git
git fetch --unshallow
git pull --all
```
然而，文件还是过大

**Comment by jshensh** [comment]
![image](https://user-images.githubusercontent.com/11555188/141642076-3818fdea-918d-4b26-b4a6-6a6061f69a7b.png)
webp 在 review 的时候还是麻烦了点。。。

**Comment by lilydjwg** [comment]
这个仓库快要2G啦：

![repo size](https://img.shields.io/github/repo-size/komeiji-satori/Dress.svg)

我以前发过一个 git bundle 的。不过那个太老了。有需要的话我再发个 bundle？
