### ISSUE TITLE
如果不便使用其他格式,仓库里的图片能不能存在git-lfs上呢

### ISSUE THREAD

**Issue by zhangyiming748** [komeiji-satori/Dress#1133]
虽然公司可以正常访问墙外网络，但是所有流量都是经过严格审查的，我住的地方即使开魔法也很难成功把项目完整克隆下来，之后如果上传的人越来越多，文件越来越大，克隆会越来越麻烦
--来自程序员的小建议

**Comment by lwd-temp** [comment]
Git-LFS如果是GitHub的那个服务的话好像是有使用限额的，每月几个GB流量而且好像都会算在仓库所有者的账户上。
有可能多几个人参与然后限额就满了
详见：
https://docs.github.com/cn/repositories/working-with-files/managing-large-files/about-storage-and-bandwidth-usage
https://docs.github.com/cn/repositories/working-with-files/managing-large-files/collaboration-with-git-large-file-storage

> 每个使用 Git Large File Storage 的帐户都会获得 1 GB 的免费存储空间和一个月的免费带宽 1 GB。 如果带宽和存储配额不够，您可以选择为 Git LFS 购买额外配额。

> 如果使用的存储空间超过 1 GB 而又未购买数据包，您仍可克隆包含大资产的仓库，但只能检索指针文件，而不能推送新文件备份。

> 如果每月使用的带宽超过1 GB而又未购买数据包，Git LFS 支持会对您的帐户禁用至下个月。

> 将大文件推送到仓库复刻会计入父仓库的带宽和存储配额，而不是复刻所有者的配额。

> 

>

**Comment by jshensh** [comment]
owner 目前失联，操作不了
