### ISSUE TITLE
get 简历：参与github 超过1.5k star的开源项目 

### ISSUE THREAD

**Issue by huqi1** [komeiji-satori/Dress#115]
get 简历：参与github 超过1.5k star的开源项目

**Comment by rekols** [comment]
66666666666666

**Comment by xiaozhi** [comment]
6666

**Comment by Trumeet** [comment]
说道六.....

**Comment by renxinlin** [comment]
已经过4K了，我都不敢fork一下

**Comment by bxlt** [comment]
可怕

**Comment by zhang199096** [comment]
只敢star  没胆fork

**Comment by plqin-xiaohao** [comment]
![image](https://user-images.githubusercontent.com/41833007/51659638-16627080-1fe6-11e9-8abe-01bc6e9034e6.png)

**Comment by shaojunluo** [comment]
勇敢folk把第一个pull request贡献出去了！
