### ISSUE TITLE
创建新分支用以其他贡献者克隆

### ISSUE THREAD

**Issue by LittleYe233** [komeiji-satori/Dress#1169]
# 问题描述

仓库的 [README](/) 中对贡献者的指引有如下说明：

> 你可以从这里学习从克隆项目，创建分支，提交和同步修改，到合并分支请求的整套流程，一次即可熟悉 Git/GitHub 的使用。

而 issue #494 中提到：

> 因为现在master分支里的object实在太多，clone体验极差。

现在若直接 clone 本仓库，需要获取的对象有六千余个；即便是在 clone 、 pull 、 fetch 时添加 `--depth 1` 参数，也仅剔除了约三分之二的对象。对后续的贡献者来说，简单地 clone 本仓库可能需要漫长的时间和较大的磁盘空间。

# 目的

本提案的主要目的是从 master 分支的早期提交处创建新分支，用以后续贡献者 clone 。

# 实现方法

## 上游维护者

上游维护者创建的分支需要满足的条件是：

- 提交数尽可能少，保证 clone 、 pull 、 merge 等的速度快、占用磁盘空间小；
- 能通过最新的 CI （见 issue #993 ，避免对后续贡献者的 pull requests 造成影响）。

## 贡献者

贡献者作出贡献的方法如下（假设贡献者用户名为 `user` ，上游维护者创建出的分支为 `clone` ）：

1. Fork 本仓库；
2. 终端中执行 `git clone --single-branch -b clone git@github.com:user/Dress.git` ；
3. 修改 `Dress` 文件夹中的内容；
4. 终端中依次执行 `cd Dress` `git add ...` `git commit ...` `git push origin clone` ；
5. 在 GitHub 中进入贡献者仓库，发起 pull request 从本地 clone 分支到上游 master 分支。

# 预期结果

贡献者只需要 clone 极少的仓库内容（ `clone` 分支）即可做出贡献。

**Comment by mmdjiji** [comment]
支持，现在clone效率太低了，其实我觉得更好的做法是把图片存在contributor自己的仓库里，然后在这里commit图片的url（虽然有可能造成项目不完整，但是还保证了contributor随时想删除都能删除）

**Comment by jshensh** [comment]
让 owner 决定吧

**Comment by hyhcrh** [comment]
> 让 owner 决定吧
komeiji-satori的简介上写着：
> This account has been voided.
这意味着owner账号本身已经干不了任何事了，即便是owner的新号也无妨，因为GitHub认为“这二位”不是一个人……
当然，如果有owner的支持是非常棒的哈，这样我们就可以实现其他可行的方法

**Comment by hyhcrh** [comment]
> 让 owner 决定吧  
komeiji-satori的简介上写着：  
> This account has been voided.  
这意味着owner账号本身已经干不了任何事了，即便是owner的新号也无妨，因为GitHub认为“这二位”不是一个人……  
当然，如果有owner的支持是非常棒的哈，这样我们就可以实现其他可行的方法

**Comment by hyhcrh** [comment]
> 让 owner 决定吧

komeiji-satori的简介上写着：
> This account has been voided.

这意味着owner账号本身已经干不了任何事了，即便是owner的新号也无妨，因为GitHub认为“这二位”不是一个人……
当然，如果有owner的支持是非常棒的哈，这样我们就可以实现其他可行的方法

**Comment by komeiji-satori** [comment]
> > 让 owner 决定吧
> 
> komeiji-satori的简介上写着：
> 
> > This account has been voided.
> 
> 这意味着owner账号本身已经干不了任何事了，即便是owner的新号也无妨，因为GitHub认为“这二位”不是一个人…… 当然，如果有owner的支持是非常棒的哈，这样我们就可以实现其他可行的方法

我还活着呢

**Comment by mmdjiji** [comment]
tql，owner来了，来重构叭

**Comment by akinazuki** [comment]
关于对仓库重构的想法 大家可以加入 [Telegram群组](https://t.me/+NQPy9sXtCkc4MmVl) 进行讨论

**Comment by BBleae** [comment]
> # 问题描述
> 仓库的 [README](/) 中对贡献者的指引有如下说明：
> 
> > 你可以从这里学习从克隆项目，创建分支，提交和同步修改，到合并分支请求的整套流程，一次即可熟悉 Git/GitHub 的使用。
> 
> 而 issue #494 中提到：
> 
> > 因为现在master分支里的object实在太多，clone体验极差。
> 
> 现在若直接 clone 本仓库，需要获取的对象有六千余个；即便是在 clone 、 pull 、 fetch 时添加 `--depth 1` 参数，也仅剔除了约三分之二的对象。对后续的贡献者来说，简单地 clone 本仓库可能需要漫长的时间和较大的磁盘空间。
> 
> # 目的
> 本提案的主要目的是从 master 分支的早期提交处创建新分支，用以后续贡献者 clone 。
> 
> # 实现方法
> ## 上游维护者
> 上游维护者创建的分支需要满足的条件是：
> 
> * 提交数尽可能少，保证 clone 、 pull 、 merge 等的速度快、占用磁盘空间小；
> * 能通过最新的 CI （见 issue [为什么我的Pr无法通过CI？ #993](https://github.com/komeiji-satori/Dress/issues/993) ，避免对后续贡献者的 pull requests 造成影响）。
> 
> ## 贡献者
> 贡献者作出贡献的方法如下（假设贡献者用户名为 `user` ，上游维护者创建出的分支为 `clone` ）：
> 
> 1. Fork 本仓库；
> 2. 终端中执行 `git clone --single-branch -b clone git@github.com:user/Dress.git` ；
> 3. 修改 `Dress` 文件夹中的内容；
> 4. 终端中依次执行 `cd Dress` `git add ...` `git commit ...` `git push origin clone` ；
> 5. 在 GitHub 中进入贡献者仓库，发起 pull request 从本地 clone 分支到上游 master 分支。
> 
> # 预期结果
> 贡献者只需要 clone 极少的仓库内容（ `clone` 分支）即可做出贡献。

有没有一种可能，克隆的时候加上 `--filter=blob:none` 参数就能省下下载大量图片的时间？
