### ISSUE TITLE
只有女装大佬吗{doge}

### ISSUE THREAD

**Issue by Snowfly-Guo** [komeiji-satori/Dress#1177]

**Comment by hyhcrh** [comment]
不 当前管理员jshensh就真的是女的
而且毕竟CONTRIBUTING.md上写了性别不限嘛

**Comment by jshensh** [comment]
> 不 当前管理员jshensh就真的是女的 而且毕竟CONTRIBUTING.md上写了性别不限嘛

（他们只对大佬感兴趣

**Comment by Maxyjof** [comment]
哈哈哈哈哈哈哈哈哈

**Comment by Luna5ama** [comment]
还有mtf（

**Comment by hyhcrh** [comment]
> 还有mtf（

啊对对对）

**Comment by itqihou** [comment]
Are you all European and American?

**Comment by Snowfly-Guo** [comment]
@itqihou we are  Chinese
