### ISSUE TITLE
让 `Imgbot` 帮忙自动无损压缩图片大小

### ISSUE THREAD

**Issue by Giftia** [komeiji-satori/Dress#1255]
仓库大小已经不可同日而语，亟需压缩一波仓库大小。

Imgbot 默认的无损压缩效果很不错，而且是提交后无感自动提mr，建议使用： [https://github.com/apps/imgbot](https://github.com/apps/imgbot) @akinazuki

**Comment by akinazuki** [comment]
已启用

**Comment by ncwhale** [comment]
感谢提供工具指引，给自己的博客也添加了，正在测试效果喵~
