### ISSUE TITLE
这个仓库是否有对图片等二进制文件设置Git Large File Storage (LFS)属性？

### ISSUE THREAD

**Issue by cw1997** [komeiji-satori/Dress#1272]
我看现在这个repo的.git文件夹非常大
![image](https://user-images.githubusercontent.com/11588555/181640997-7629cb10-7f89-42bc-ac4e-0f5bafb78299.png)
拉取速度也很慢，我怀疑可能是因为没有设置LFS，所以经过多人长期修改后导致这个仓库的磁盘空间占用比较大？建议可以通过.gitattributes为各种常见图片的扩展名设置LFS属性，以提升性能和降低磁盘空间占用。

**Comment by lilydjwg** [comment]
然后由于达到 [GitHub LFS 的流量限制](https://docs.github.com/cn/repositories/working-with-files/managing-large-files/about-storage-and-bandwidth-usage)，大家都下载不了啦。

**Comment by cw1997** [comment]
> 然后由于达到 [GitHub LFS 的流量限制](https://docs.github.com/cn/repositories/working-with-files/managing-large-files/about-storage-and-bandwidth-usage)，大家都下载不了啦。

好吧，原来GitHub还有这种限制
