### ISSUE TITLE
请求管理员更新我的账户权限

### ISSUE THREAD

**Issue by kagurazakayashi** [komeiji-satori/Dress#1293]
我一直有处理 Pull requests 的权限，但是我对此项目 PR 等的回复和对 PR 的操作之后，感觉有点影响我对 Github 的使用（比如历史记录什么的），所以其实处理 PR 也不多。
我希望能把我这个账户的相关权限给予我的另一个账户 @kaguramiyabiw ，希望管理员能操作一下。

**Comment by komeiji-satori** [comment]
好啦
