### ISSUE TITLE
恶心死我了

### ISSUE THREAD

**Issue by 1010663814** [komeiji-satori/Dress#1322]
网络不是法外之地，这么恶心的项目必须受到法律制裁。

**Comment by Giftia** [comment]
网络不是法外之地，请您遵守 GitHub 使用政策，以及接受我对您的道德谴责😁

[GitHub 仇恨言论和歧视](https://docs.github.com/zh/site-policy/acceptable-use-policies/github-hate-speech-and-discrimination)
```
GitHub 不允许基于个人或群体的身份攻击或煽动仇恨的言论，包括年龄、体型、能力、种族、性别认同和表达、经验水平、国籍、个人外表、种族、宗教、性身份或性取向。这包括：

- 根据个人或团体的信仰或上述特征嘲笑、攻击或排斥他们
- 显示与已知的恐怖主义或暴力极端主义组织的明确隶属关系或身份
- 支持或宣传仇恨团体或基于仇恨的阴谋论
- 分享与仇恨同义的符号或图像
- 使用有害的刻板印象、诽谤或不人道的言论
- 根据感知的性别攻击个人
- 狗吹口哨；或使用编码或暗示性语言和/或符号来宣扬虐待或仇恨

虽然 GitHub 严肃对待平台上的所有虐待和骚扰事件，但我们特别致力于打击基于仇恨的虐待，因为它不成比例地影响了历史上曾成为此类虐待目标的社区。我们的目标是让 GitHub 成为所有人都感到受欢迎和安全的地方。
```

[GitHub 上的欺凌和骚扰](https://docs.github.com/zh/site-policy/acceptable-use-policies/github-bullying-and-harassment)
```
我们不容忍任何形式的骚扰、欺凌或虐待，无论是直接还是鼓励他人参与违禁行为。 其中包括：

- 针对性的人身攻击
- 以近乎于虐待的方式实施或策划[破坏性](https://docs.github.com/zh/github/site-policy/github-disrupting-the-experience-of-other-users)活动
- 以一种会导致威胁的方式关注平台上的其他用户
- 发出针对他人的性骚扰或性评论
- 以煽动冲突或破坏真诚讨论的方式虚伪地参与对话
- 创建专门用于逃避 GitHub 员工或用户采取的审核操作的备用帐户

请注意，并非所有不受欢迎的行为都一定被视为骚扰。 例如，与其他用户意见不一致或对他们的评论投反对票可能不会上升到我们平台上的骚扰级别。 此外，分享对公众人物或公共项目或公众感兴趣的话题的批评，并不一定受此政策约束。 然而，我们建议您注意您与其他用户和平台的互动方式，因为此活动仍可能违反我们对破坏其他用户体验的限制。
```

**Comment by woshishabii** [comment]
> 

什么猫病

**Comment by Giftia** [comment]
```yaml 
彭竣竣: 男，30岁，生于1990年7月2日，江西省赣州市宁都县人
```

**Comment by woshishabii** [comment]
> 网络不是法外之地，这么恶心的项目必须受到法律制裁。

请问哪条法律条文规定这是违法的？

**Comment by Angelic47** [comment]
同志，看来您是懂法的，那么原谅我来给您一个法律建议。
如果您觉得这个issue恶心，您完全可以点击浏览器右上角，并人脑拉黑这个项目的所有相关id，永远不要使用与该项目参与人员有关的任何代码——这是法律赋予你的权利。
而不是发一句辱骂性的言论来泄私愤，这是完全错误的结果。根据《民法典》第一千零二十四条规定：民事主体享有名誉权，任何组织或者个人不得以侮辱、诽谤等方式侵害他人名誉权。
因此，您的这个行为可能涉嫌触犯民法典。您试图在通过自己的主观臆测对他人的名誉进行无任何证据上的攻击，可真实情况往往与您的主观臆测相背离。在这种情况下，您很可能“侵犯名誉权”而被他人提起诉讼。
此外，若您的这个行为还导致了其他人严重心理疾病，如抑郁等，您可能触犯《刑法》第二百四十六条而被他人提起刑事自诉，等待您的将是牢狱之灾。
我在这里提醒您在日常生活中注意您的行为举止。正如你所说，不只是互联网不是法外之地，现实生活更不是。
若本项目的任意内容让您感到暂不能接受，您应该直接关闭。这是最简单而且最占理的做法。所有的律师朋友应该都跟您讲过“不要把本来有理的事情搞得没理了”。您做其他事情亦应当如此。

**Comment by lxgw** [comment]
（此处 bgm：惊涛落日）
