### ISSUE TITLE
希望页面能加入webp支持

### ISSUE THREAD

**Issue by kagurazakayashi** [komeiji-satori/Dress#144]
我也在考虑要不要全都传成 jpg 格式的，毕竟我也感觉从 webp 生成缩略图确实有些难度

目前 webp 格式状况：
- drsrel.github.io
  - 未收录 webp 格式图片
- satori.mycard.moe
  - NET::ERR_CERT_DATE_INVALID
- wearadress.org
  - 已收录，但是没有缩略图

**Comment by kagurazakayashi** [comment]
算了，感觉现在用 webp 还是太超前了，还是继续用兼容性最好的 jpeg 好了。新的 pr 已提交。

**Comment by leewr** [comment]
照片对应的作者信息是如何拿到的？
