### ISSUE TITLE
女装数据集get

### ISSUE THREAD

**Issue by aether-rootr** [komeiji-satori/Dress#150]
那位大佬开发下女装大佬识别器啊，这里是数据集  滑稽.jpg

**Comment by kagurazakayashi** [comment]
这里的女装数据只是沧海一粟，无论是做识别还是机器学习都远远不够。
可爱就行了嘛~~

**Comment by chinaxas** [comment]
好想法

**Comment by chinaxas** [comment]
有没有人工智能大佬

**Comment by jshensh** [comment]
（然后发现训练出来的模型会把女的认成男

**Comment by jamesyangget** [comment]
> （然后发现训练出来的模型会把女的认成男

让我想起有个人发了张即像猫又像狗的图，连人也分辨不出来的那种
