### ISSUE TITLE
滥用github，这样OK？

### ISSUE THREAD

**Issue by seamount-knight** [komeiji-satori/Dress#195]

**Comment by Lionad-Morotar** [comment]
真香警告

**Comment by senayuki** [comment]
本质是帮助萌新学习使用git！
（提交者中真的有萌新么

**Comment by Misaka-0x447f** [comment]
github官方没说滥用的话，我觉得别人也没权力说。github还有人做小说的呢。

**Comment by Delete540** [comment]
> github官方没说滥用的话，我觉得别人也没权力说。github还有人做小说的呢。

那也不能当公共洗手间使用,谢谢

**Comment by cai-lw** [comment]
页面最下面Terms点进去慢慢看
如果你能找到明确的相关条款就贴出来
找不到就说明GitHub不认为这是滥用

**Comment by kanokaakiko** [comment]
我就素萌新【暂时只会回复 其他啥都不会qvq
