### ISSUE TITLE
Consider using Git LFS?

### ISSUE THREAD

**Issue by ycwei982** [komeiji-satori/Dress#204]

**Comment by LinEvil** [comment]
头像过于可爱

**Comment by ycwei982** [comment]
#274 time to do this...

**Comment by ycwei982** [comment]
Probably using Git LFS isn't a good idea, since Git LFS needs to be installed separately, this could be a bit difficult for new Git users.

The repository's goal is to teach developers how to use basic Git and GitHub, not for *pure picture sharing*.
