### ISSUE TITLE
为啥 readme 里的 Contributors 没有窝头像阿。。

### ISSUE THREAD

**Issue by jshensh** [komeiji-satori/Dress#233]
这坐靠背椅的秃头兔子 emmm

**Comment by huangjianke** [comment]
要火了🔥


**来自GitHub小程序客户端：**

![image](https://user-images.githubusercontent.com/8692455/51429898-b159f400-1c4e-11e9-91a1-59cd1fab5042.png)

**Comment by akechisatori** [comment]
![image](https://user-images.githubusercontent.com/43605695/51533793-dc2a8f00-1e7e-11e9-8855-624c8e16e3c5.png)

**Comment by jshensh** [comment]
![4fb6b93bfaca2852](https://user-images.githubusercontent.com/11555188/51533806-e3ea3380-1e7e-11e9-8713-330eea16c9cc.jpg)
#233 的 pr 可还行

**Comment by jshensh** [comment]
@akechisatori 阿是我瞎
