### ISSUE TITLE
Geotag

### ISSUE THREAD

**Issue by fakefred** [komeiji-satori/Dress#24]
Taken kingfree/2017.10.2.CICF.Nijino.Yume.jpg for example.
When parsed in photo editor, in info box shows the Geo location: (uploaded with partial data erased)
```
GPS
	23° x′ xx.xxxx″ N , 113° xx′ xx.xxxx″ E
```
And EXIF:
```
[ROOT]
	Make: 'Xiaomi'
	Model: 'MI 5'
	XResolution: 72
	YResolution: 72
	ResolutionUnit: 2
	Software: 'gemini-user 7.0 NRD90M V8.5.3.0.NAACNED release-keys'
	DateTime: '2017:10:03 13:04:34'
	YCbCrPositioning: 1
	ExifOffset: 238
	GPSInfo: 722

[EXIF]
	ExposureTime: 1/17 (0.059)
	FNumber: 2
	ExposureProgram: 0
	PhotographicSensitivity: 691
	ExifVersion: 48, 50, 50, 48
	DateTimeOriginal: '2017:10:03 13:04:34'
	DateTimeDigitized: '2017:10:03 13:04:34'
```

These info leak out precise personal data of female-dressers, (which might be good), but better erase them. The dressers should erase exif data in advance; it is not the repo maintainer's duty to protect 
~~piracy~~ privacy. 

![From xkcd.com](https://imgs.xkcd.com/comics/paperwork.png)

**Comment by komeiji-satori** [comment]
But the EXIF location is a public show （
![image](https://user-images.githubusercontent.com/18225919/39968096-247993ac-56fa-11e8-9da7-17e3b736b69f.png)

**Comment by fakefred** [comment]
Heading to Google maps.

**Comment by fakefred** [comment]
![](https://i.imgur.com/N4Sm1or.jpg)

**Comment by fakefred** [comment]
一起来独秀

**Comment by LBYPatrick** [comment]
@fakefred 说明他们需要你去他们家\*\*交...
