### ISSUE TITLE
成功加入4K Star项目 打卡

### ISSUE THREAD

**Issue by lihahaha** [komeiji-satori/Dress#249]

**Comment by Surile** [comment]
@lihahaha  ( ⊙o⊙ ) 砸看头像，感觉就是一个入坑的

**Comment by huangjianke** [comment]
welcome


**来自GitHub小程序客户端：**

![image](https://user-images.githubusercontent.com/8692455/51429898-b159f400-1c4e-11e9-91a1-59cd1fab5042.png)
