### ISSUE TITLE
竟然有 github page 惹

### ISSUE THREAD

**Issue by mudream4869** [komeiji-satori/Dress#29]
0w0 🎆

**Comment by ly0** [comment]
所以github pages在哪里

**Comment by zh99998** [comment]
不好用，每次提交都会出些bug
先下掉了.. 再另一个地方重新搭

**Comment by zh99998** [comment]
https://satori.mycard.moe

**Comment by a-wing** [comment]
@zh99998 我想个贡献下这个子域名 `dress.22333.fun` 来访问这个（（（

**Comment by MikaGuraNTK** [comment]
@a-wing 反向代理即可 :(

**Comment by KagurazakaHanabi** [comment]
每次提交后GitHub Page都要重新设置下的

**Comment by xiazeyu** [comment]
> https://satori.mycard.moe

@zh99998 大佬你的网站上什么都没有啊

试图自己build, 但是master太大了, git 速度只有100KB...

**Comment by null-moe** [comment]
@zh99998 进去什么都没有耶

**Comment by xiazeyu** [comment]
常见README.md
