### ISSUE TITLE
advice: setup a WeChat group for all the contributors.

### ISSUE THREAD

**Issue by Becavalier** [komeiji-satori/Dress#295]
Anyone who join the group should send his/her selfie first to prove that they are possible to be or already be a contributor. : )

**Comment by studentmain** [comment]
IMO, for an open source project, a mailing list is enough.

另外不要在一个社交平台推荐另一个社交平台（

**Comment by OrangePekoeTea** [comment]
The thought of having to use WeChat in any capacity is terrifying.

**Comment by harry-gzcn** [comment]
telegram最棒了！

**Comment by ycwei982** [comment]
Think about the stablest accessibility. Telegram requires a proxy or VPN, although I believe most of the contributors have one. In order to better protect privacy, IMs out of PRC are the major choice.

If common IMs are contributors IRL, then someplace like Gitter is ok.

However if VPN is down, time to find another place. 

Self-hosting an IM for this repository is worthless...

**Comment by BlueFlo0d** [comment]
> > much better than almost any other IMs
> 
> 来源请求（
> 
> 还是那句话，对于一个开源软件的开发，邮件列表够了，邮件列表又不是不能发图对吧（

I said it!
BTW, do you really think this is a software repo? I see the 天然呆 gh first think it is a Standard ML project and then Ruby... but I don't even think it is software! gh is not limited to software development, anyway.

**Comment by studentmain** [comment]
主要是在已经有全世界程序员都在用的邮件列表和issue tracker的情况下，有没有使用其他聊天软件的必要。

另外考虑到QQ和微信事实上不是透明信道，在此前提下，我认为说它们`much better than`（至少是个透明信道的）其他聊天软件是不适合的。

**Comment by BlueFlo0d** [comment]
Well I'm just talk about features and experience, as for security and freedom of course it comes to tg security chat.
y u talk like RMS, did our Lord learn Chinese and open up a cute gh (now owned by ms and server side not open source, I may call it SaaS, though RMS himself excluded sw repos for this case) account? > <

**Comment by ltoddy** [comment]
Why not slask or discord.
