### ISSUE TITLE
发展的好快啊

### ISSUE THREAD

**Issue by njlyf2011** [komeiji-satori/Dress#301]
我当初关注这个项目的时候，Star 量貌似挺低的。。。好像是三位数，转眼间就 5k 了。。。

**Comment by yinghualuowu** [comment]
一时女装一时爽，一直女装一直爽

**Comment by iReQAQ** [comment]
爽啊爽啊爽啊爽


是不是感觉和楼上很押韵？

**Comment by IreliaLi** [comment]
![Uploading https://tb2.bdstatic.com/tb/editor/images/face/i_f25.png…]()

**Comment by IreliaLi** [comment]
![avatar](https://tb2.bdstatic.com/tb/editor/images/face/i_f25.png)
