### ISSUE TITLE
我可以只发小裙子丝袜的腿照吗？

### ISSUE THREAD

**Issue by Icarus-snow** [komeiji-satori/Dress#304]
蓝孩纸，我可以只发小裙子丝袜的腿照吗？

**Comment by kagurazakayashi** [comment]
怎么可能没有腿子 ![](https://camo.githubusercontent.com/52a3c61c168fcb496dce3c576908ed6d4df830d5/68747470733a2f2f7462322e62647374617469632e636f6d2f74622f656469746f722f696d616765732f666163652f695f6632352e706e67)
找找就有了w

**Comment by XHidamariSketchX** [comment]
善

**Comment by ycwei982** [comment]
这个仓库里有成百上千张

**Comment by XHidamariSketchX** [comment]
你发PR吧w
