### ISSUE TITLE
雅诗你怎么有胸？？

### ISSUE THREAD

**Issue by WUID** [komeiji-satori/Dress#306]
https://wearadress.org/KagurazakaYashi/Yashi20160407DSC6668E.jpg

**Comment by XHidamariSketchX** [comment]
胸当然是个插件啦。可扩展性是很重要的哦

**Comment by WUID** [comment]
这是怎么做到的？？

**Comment by studentmain** [comment]
高度可缩放架构

**Comment by kagurazakayashi** [comment]
义乳
`yashi install falsies -y`

**Comment by gongym12138** [comment]
图片里是个男的？我是真滴不信。。。

**Comment by studentmain** [comment]
> 图片里是个男的？我是真滴不信。。。

自己复现一下嘛，相关配置方法都有教程，复现完了记得把结果发出来。

**Comment by Trumeet** [comment]
这就是大佬吧（

**Comment by kagurazakayashi** [comment]
其实我这张照片确实也有故意挡肩宽的操作www

**Comment by Trumeet** [comment]
> 其实我这张照片确实也有故意挡肩宽的操作www

dalao！（所以胸是怎么回事呢..

**Comment by FrankHB** [comment]
……前川みく？
https://www.pixiv.net/member_illust.php?mode=medium&illust_id=54911277

**Comment by CTCS-4** [comment]
> 其实我这张照片确实也有故意挡肩宽的操作www

或许这就是dalao吧......
`yashi configure --hide-shoulder`

**Comment by lengfeng1224** [comment]
> 义乳
> `yashi install falsies -y`

大佬我们做朋友吧

**Comment by silvasaga** [comment]
拜服......

**Comment by linkdesu** [comment]
> 义乳
> `yashi install falsies -y`

推上关注很久，今天意外发现还有 github 账号，fo 一个 :joy:
