### ISSUE TITLE
提议：将照片数<=n的文件夹归入一个归档文件夹

### ISSUE THREAD

**Issue by Misaka-0x447f** [komeiji-satori/Dress#330]
虽然知道提出这样的建议可能会被喷但是。
目前仓库中存在着大量的仅有寥寥数张照片的文件夹，且没有连载的迹象。
为了方便直接在目录中阅览，是否有必要将较少照片的文件夹归入一个归档文件夹中？
个人建议n<=3。

**Comment by studentmain** [comment]
直接在资源管理器里面查找一下就可以“在目录中”浏览了。我觉得用不着

**Comment by Misaka-0x447f** [comment]
并不是每一个人都会把整个仓库拖下来吧...
也许有些人只是想在github上浏览

**Comment by ncwhale** [comment]
使用 [Octotree](https://chrome.google.com/webstore/detail/octotree/bkhaagjahfmjljalopjnoealnfndnagc?hl=en-US) 的用户表示毫无压力喵~

**Comment by lilydjwg** [comment]
使用 [Octotree](https://addons.mozilla.org/firefox/addon/octotree/) 的火狐用户飘过～
