### ISSUE TITLE
好像很多人还不知道，要投稿不用一下子全都克隆下来

### ISSUE THREAD

**Issue by kagurazakayashi** [komeiji-satori/Dress#380]
已经会了的大佬请无视掉，没用过这个功能的可以尝试一下。
如果连克隆都不会可以看我之前发的视频： #66

这里介绍一下操作步骤：

1. Fork 项目，先不着急克隆到本地，而是在本地新建一个仓库！首先，创建项目文件夹，初始化仓库。
```
$ mkdir dress
$ cd dress
$ git init
已初始化空的 Git 仓库于 /Volumes/RamDisk/dress/.git/
```
2. 然后，从 Github 上复制 HTTPS 或 SSH 同步网址，并告诉这个仓库：
![](https://www.yoooooooooo.com/yashi/wp-content/uploads/2019/02/20190210180357.png)
```
$ git remote add -f origin https://github.com/kagurazakayashi/Dress.git
更新 origin 中
remote: Enumerating objects: 8, done.
remote: Counting objects: 100% (8/8), done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 2863 (delta 1), reused 2 (delta 0), pack-reused 2855
接收对象中: 100% (2863/2863), 872.37 MiB | 322.00 KiB/s, 完成.
处理 delta 中: 100% (997/997), 完成.
来自 https://github.com/kagurazakayashi/Dress
* [新分支] gh-pages -> origin/gh-pages
* [新分支] master -> origin/master
* [新分支] web -> origin/web
```
遗憾的是，这仍然花掉了很多时间，还是传输了很多的内容下来。不过，这比起按 GB 计算的总项目大小，已经轻松很多了。
![](https://www.yoooooooooo.com/yashi/wp-content/uploads/2019/02/20190210203438.png)
可以看到，这个文件夹里什么都没有（有一个隐藏的 .git 文件夹），目前确实是没有下载这些文件。

3. 于是，下面重点来了，将这个本地库设置为「稀疏模式」吧：
`$ git config core.sparsecheckout true`
什么都没有返回就是正常了。

4. 接下来就要告诉 git ，你需要同步哪些文件下来了，创建配置文件 sparse-checkout ，去里面指定你要同步的文件夹吧（不会用 vim 的话用其他纯文本处理软件也可）：
`$ vim .git/info/sparse-checkout`
例如，我只要同步项目里的「KagurazakaYashi」文件夹，只要这样填就 OK 了，注意后面加上「/」：
![](https://www.yoooooooooo.com/yashi/wp-content/uploads/2019/02/20190210204243.png)

5. 然后，用这个命令开始同步试试：
```
$ git pull origin master
来自 https://github.com/kagurazakayashi/Dress
* branch master -> FETCH_HEAD
```
可以看到，本地项目文件夹里只有这个文件夹出现了。
![](https://www.yoooooooooo.com/yashi/wp-content/uploads/2019/02/20190210205347.png)

6. 下面，我再加入一个项目中没有的文件夹「yashi」：
![](https://www.yoooooooooo.com/yashi/wp-content/uploads/2019/02/20190210205639.png)
```
$ git pull origin master
来自 https://github.com/kagurazakayashi/Dress
* branch master -> FETCH_HEAD
已经是最新的。
```
注意，如果只设置一个没有的文件夹，会又到一句提示：
`error: Sparse checkout leaves no entry on working directory`
它只是提醒一下你没有什么可同步的而已，无视掉就好。

7. 接下来，我们创建这个文件夹，并随便拷贝个文件进去以测试：
```
$ mkdir yashi
$ cp /Volumes/RamDisk/SAM0218.jpg yashi/
```

8. 然后新增这个文件到暂存，并查看状态：
```
$ git add .
$ git status
位于分支 master
要提交的变更：
（使用 "git reset HEAD <文件>..." 以取消暂存）
新文件： yashi/SAM0218.jpg
```

9. 可以看到刚才新增的文件已经在里面了，让我们提交看看：
```
$ git push
fatal: 当前分支 master 没有对应的上游分支。
为推送当前分支并建立与远程上游的跟踪，使用
git push --set-upstream origin master
```

10. 根据这个提示，输入这个命令，会提示你输入 github 的用户名和 Personal access tokens （如果开启账户安全，否则直接输入密码），只有这次 push 的时候需要这样设置一下：
```
$ git push --set-upstream origin master
Username for 'https://github.com': kagurazakayashi
Password for 'https://kagurazakayashi@github.com':
枚举对象: 5, 完成.
对象计数中: 100% (5/5), 完成.
使用 4 个线程进行压缩
压缩对象中: 100% (3/3), 完成.
写入对象中: 100% (4/4), 413.30 KiB | 15.31 MiB/s, 完成.
总共 4 （差异 1），复用 0 （差异 0）
remote: Resolving deltas: 100% (1/1), completed with 1 local object.
To https://github.com/kagurazakayashi/Dress.git
a508d04..ecd8f89 master -> master
分支 'master' 设置为跟踪来自 'origin' 的远程分支 'master'。
```

11. 可以在网页上看到，提交已经成功了。
![](https://www.yoooooooooo.com/yashi/wp-content/uploads/2019/02/20190210211941.png)

转自 [我的博客](https://www.yoooooooooo.com/yashi/5659)，如果图片无法载入请点此去我博客看。

**Comment by ShirasawaSama** [comment]
1. 点一下fork
2. 直接在网页上点`create new file` 文件名输入 `你的名字/啥都行` (**注意中间的斜杠**)
3. 然后底下写一下commit信息 然后点一下提交
4. 进入你创建的文件夹 点 `upload file`
5. 拖文件进去 点提交 填写commit信息
6. 发pr等合并
好了

**Comment by lilydjwg** [comment]
呃，其实 sparse checkout 只是 checkout 这一步不检出一大堆文件，相关的 git 对象还是都获取了的。也就是省了磁盘空间，并没有省下载。

**Comment by bangbang93** [comment]
要想减少clone体积，请使用--depth 参数
`git clone git@github.com:komeiji-satori/Dress.git --depth 1`
这样本地只会保留最近一条commit，不会把历史拉下来。
截止目前大约会减少300M的下载（884M/512M）

**Comment by Sicmatr1x** [comment]
全部克隆出来也好, 分布式存储嘛

**Comment by kagurazakayashi** [comment]
> 1. 点一下fork
> 2. 直接在网页上点`create new file` 文件名输入 `你的名字/啥都行` (**注意中间的斜杠**)
> 3. 然后底下写一下commit信息 然后点一下提交
> 4. 进入你创建的文件夹 点 `upload file`
> 5. 拖文件进去 点提交 填写commit信息
> 6. 发pr等合并
>    好了

我都忘了，可以这样！
这样简单方便的方法我完全没有想到！

**Comment by madobet** [comment]
> 1. 点一下fork
> 2. 直接在网页上点`create new file` 文件名输入 `你的名字/啥都行` (**注意中间的斜杠**)
> 3. 然后底下写一下commit信息 然后点一下提交
> 4. 进入你创建的文件夹 点 `upload file`
> 5. 拖文件进去 点提交 填写commit信息
> 6. 发pr等合并
>    好了

这样会失去练习使用 git 命令的机会！真的变成女装仓库了（难道之前不是吗
