### ISSUE TITLE
我要不要把体积过大的照片压缩一下？

### ISSUE THREAD

**Issue by kagurazakayashi** [komeiji-satori/Dress#41]
我发现我传的照片质量太高了：
- 大部分在 `10 MB - 20 MB` 区间。
- 我一个人就用了 `132 MB` 。

感觉这已经影响到别人 `Clone` 体验了，我要不要压缩一下？比如：
- 减少图片尺寸到至多 `1080P` 。
- 使用 `WEBP` 格式，并进行更高级别的有损压缩。

如果需要这样做的话：
- 一张照片多大体积比较合适？
- 一张照片多大尺寸比较合适？

**Comment by littleplus** [comment]
不，原图，不要压缩，谢谢（手动滑稽）

**Comment by bangbang93** [comment]
没事，硬盘不值钱

**Comment by soruly** [comment]
GitHub好像有1GB的repo size限制

**Comment by kagurazakayashi** [comment]
根据 Github 的 [有关说明](https://help.github.com/articles/what-is-my-disk-quota/) : `We recommend repositories be kept under 1GB each.` 
虽然只是建议而不是强制限制，但是如果按1GB来计算的话我占了十分之一，所以我还是决定减少一下文件体积，防止项目创建者收到警告邮件。
我会在近期进行 webp 有损压缩并增加一些新的东西。

**Comment by Genteure** [comment]
#42 除非从仓库中彻底删除旧 commit，否则总仓库大小不会因为当前 commit 大小变小而变小。
可以考虑新开一个原始分辨率仓库储存压缩前的图片，单仓库大小问题可以用 git submodule 把内容分散到多个仓库

**Comment by kagurazakayashi** [comment]
噢，那就没办法了，至少从现在开始我统一用压缩后的图片好了。以后不传那么大尺寸的文件了。
