### ISSUE TITLE
求教

### ISSUE THREAD

**Issue by 12yy296** [komeiji-satori/Dress#502]
我需要一个具体的，完整的教程与推荐！

**Comment by Misaka-0x447f** [comment]
什么东西的教程

**Comment by 12yy296** [comment]
当然是女装的教程与推荐/xyx

**Comment by Misaka-0x447f** [comment]
加个这类的群吧……
女装底子是一部分搭配发型是一部分……
没什么可教的……你需要明确要学的是什么，比如，你要学简单日常化妆，或者你要学服装搭配，或者你要了解脱毛知识。
