### ISSUE TITLE
我也想女装了,但是我要控制我自己,控制!!!

### ISSUE THREAD

**Issue by Yangdaidai** [komeiji-satori/Dress#521]
我也想女装了,但是我要控制我自己,控制!!!

**Comment by studentmain** [comment]
对于这种新技术，要勇于尝试嘛

**Comment by shenlanAZ** [comment]
# 如何控制女装

## 思路
1. 多看女装（先让自己的神经麻木）
2. 买一套女装（无非也就是几块布拼凑在一起而已）
3. 穿上女装（满足心理需求）
4. 拍照（这是个成就 得截图）
5. 脱下女装（保证自己不会再女装 并且丢掉女装）
6. 成功控制女装

## 实践

**不用想了，女装只有零次和无数次。我已经买了几套了.....**

~~~java

while(true){
  女装()
}
~~~~

**Comment by Fakeeer** [comment]
不要尝试，试试就逝世！-！

**Comment by ovomiao** [comment]
为什么要控制，毕竟女装辣么好看(/ω＼)

**Comment by whosmyqueen** [comment]
直接穿女朋友的衣服不就行了

**Comment by Yangdaidai** [comment]
单身狗，穿不了🤣🤣🤣------------------ 原始邮件 ------------------
发件人: "郑志辉"<notifications@github.com>
发送时间: 2019年11月7日(星期四) 上午10:26
收件人: "komeiji-satori/Dress"<Dress@noreply.github.com>;
抄送: "Yangdaidai"<1024826067@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [komeiji-satori/Dress] 我也想女装了,但是我要控制我自己,控制!!! (#521)



直接穿女朋友的衣&#x670D;不就行了
 
&mdash;

**Comment by 13853158735** [comment]
释放你的天性！

**Comment by madobet** [comment]
这世上没有男装女装，只有穿着合适或者不合适的衣服

**Comment by Yangdaidai** [comment]
哈哈哈，怕了怕了------------------ 原始邮件 ------------------
发件人: "Tooko Madobe"<notifications@github.com>
发送时间: 2019年12月20日(星期五) 晚上8:43
收件人: "komeiji-satori/Dress"<Dress@noreply.github.com>;
抄送: "Yangdaidai"<1024826067@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [komeiji-satori/Dress] 我也想女装了,但是我要控制我自己,控制!!! (#521)



这世上没有男装女装，只有穿着合适或者不合适的衣&#x670D;
 
&mdash;
