### ISSUE TITLE
女装质量限制

### ISSUE THREAD

**Issue by PhotonQuantum** [komeiji-satori/Dress#528]
提pr有女装的质量限制嘛 不是指图片文件的质量 指的是女装的质量ヾ (´･ω･｀)ﾉ

**Comment by RapeCat** [comment]
看起来 只要是认真的 应该都能过QwQ

**Comment by kagurazakayashi** [comment]
一般只要不是质量太低，甚至故意瞎眼的，还是很容易过的。
一般对不太自信的地方进行图片裁剪或者图片贴纸遮挡就好。

**Comment by oO0oO0oO0o0o00** [comment]
捕捉雅诗大姐姐~
