### ISSUE TITLE
女装只有零次和无数次!!!

### ISSUE THREAD

**Issue by tmlh98** [komeiji-satori/Dress#542]

**Comment by zhulinmx** [comment]
hhhhh，因为越来越找到自我zzz

**Comment by tmlh98** [comment]
> hhhhh，因为越来越找到自我zzz

小姐姐是抱着一个怎样的心态过来的?

**Comment by zhulinmx** [comment]
> > hhhhh，因为越来越找到自我zzz
> 
> 小姐姐是抱着一个怎样的心态过来的?

试图窥探一下现在蓝孩纸的内心世界

**Comment by tmlh98** [comment]
> > > hhhhh，因为越来越找到自我zzz
> > 
> > 
> > 小姐姐是抱着一个怎样的心态过来的?
> 
> 试图窥探一下现在蓝孩纸的内心世界

紧张又刺激

**Comment by oO0oO0oO0o0o00** [comment]
QAQ

**Comment by zhulinmx** [comment]
> > > > hhhhh，因为越来越找到自我zzz
> > > 
> > > 
> > > 小姐姐是抱着一个怎样的心态过来的?
> > 
> > 
> > 试图窥探一下现在蓝孩纸的内心世界
> 
> 紧张又刺激

现在都十分留意身边的男程序员，谁知道某些人表面深沉，背地里女装大佬

**Comment by tmlh98** [comment]
> > > > > hhhhh，因为越来越找到自我zzz
> > > > 
> > > > 
> > > > 小姐姐是抱着一个怎样的心态过来的?
> > > 
> > > 
> > > 试图窥探一下现在蓝孩纸的内心世界
> > 
> > 
> > 紧张又刺激
> 
> 现在都十分留意身边的男程序员，谁知道某些人表面深沉，背地里女装大佬

指桑骂槐、指鹿为马，指纹解锁...

**Comment by xw3091** [comment]
和有趣的人交朋友

**Comment by chenleigang** [comment]
> > > > > hhhhh，因为越来越找到自我zzz
> > > > 
> > > > 
> > > > 小姐姐是抱着一个怎样的心态过来的?
> > > 
> > > 
> > > 试图窥探一下现在蓝孩纸的内心世界
> > 
> > 紧张又刺激
> 
> 现在都十分留意身边的男程序员，谁知道某些人表面深沉，背地里女装大佬

你好那啥呀
