### ISSUE TITLE
好奇问下：女装大佬们的性取向是？？？

### ISSUE THREAD

**Issue by kiinlam** [komeiji-satori/Dress#555]
好奇害死猫

**Comment by AyagawaSeirin** [comment]
这个还是因人而异的，是否女装和性取向没有关系。

**Comment by jshensh** [comment]
大部分女孩子的性取向是男，大部分男孩子的性取向是女，小部分人是双

**Comment by AyagawaSeirin** [comment]
> 大部分女孩子的性取向是男，大部分男孩子的性取向是女，小部分人是双

还有同

**Comment by supertankhzt** [comment]
> > 大部分女孩子的性取向是男，大部分男孩子的性取向是女，小部分人是双
> 
> 还有同

还有小小部分无性恋

**Comment by AyagawaSeirin** [comment]
唉，LGBT在中国的处境仍然不乐观呢

**Comment by Lhcfl** [comment]
其实我感觉在这里提交的有不少是MtF……

**Comment by AyagawaSeirin** [comment]
> 其实我感觉在这里提交的有不少是MtF……

emmmmm...我就是

**Comment by Lhcfl** [comment]
> > 其实我感觉在这里提交的有不少是MtF……
> 
> emmmmm...我就是

emmmm我见过你blog（还记得我吗）

我在怀疑我是不是QwQ

**Comment by AyagawaSeirin** [comment]
> > > 其实我感觉在这里提交的有不少是MtF……
> > 
> > 
> > emmmmm...我就是
> 
> emmmm我见过你blog（还记得我吗）
> 
> 我在怀疑我是不是QwQ

当然记得啦qwq
判断自己的话...这个要认真仔细qwq毕竟能完全的认识自己也是件好事

**Comment by yeyu443** [comment]
> 其实我感觉在这里提交的有不少是MtF的......

我就在跨性别群里看到这个的。

**Comment by liunima1129** [comment]
> > 其实我感觉在这里提交的有不少是MtF……
> 
> emmmmm...我就是

transgender吗

**Comment by clys** [comment]
> 我尼玛还是不够变态，显得跟你们有点格格不入！哈哈 ...

这不叫变态

**Comment by miryuan** [comment]
我在想要不要克隆这个项目到本地,我怕污了我的眼睛
