### ISSUE TITLE
女装大佬  是啥 ？ 男孩子穿女装那种嘛？？？

### ISSUE THREAD

**Issue by ChengKeJ** [komeiji-satori/Dress#556]
女装大佬  是啥 ？ 男孩子穿女装那种嘛？？？

**Comment by kagurazakayashi** [comment]
https://zh.wikipedia.org/wiki/女装大佬
https://zh.moegirl.org/女装大佬

**Comment by madobet** [comment]
有一种东西叫百度，机智点朋友还知道谷歌
![77689b139b05e087.gif](https://i.loli.net/2019/12/20/yOLa7IkUhjmZqvn.gif)

**Comment by ygxdxx10** [comment]
![MAKEUP_2020020201061067_save](https://user-images.githubusercontent.com/61280522/74943787-ddfdb380-53ec-11ea-9136-f649b407bd00.jpg)
你们好，想你(っ ̯ -｡)
