### ISSUE TITLE
诚心交友, 素质单男, 微博 @勃酱, 直接私聊即可.

### ISSUE THREAD

**Issue by KFERMercer** [komeiji-satori/Dress#558]
![U%RGJ`2%1}5X7SCY %0 JXJ](https://user-images.githubusercontent.com/37098748/61578033-03f36a80-ab23-11e9-95ba-524020e97d6d.png)

**Comment by KFERMercer** [comment]
## 母胎单身十八年，不羡女郎只识男。
好想有一个灵魂伴侣。。在这里能找到吗。。有意的私聊[微博](https://weibo.com/u/6072877891?from=feed&loc=at&nick=%E5%8B%83%E9%85%B1)吧，确定诚意的再加微信。。

**Comment by KFERMercer** [comment]
我不是骗子。。

**Comment by jshensh** [comment]
？？？
