### ISSUE TITLE
完了 学编程必须要女装 但是我是女的咋办

### ISSUE THREAD

**Issue by liunima1129** [komeiji-satori/Dress#560]

**Comment by kagurazakayashi** [comment]
https://github.com/greenaway07/GirlDress

**Comment by jshensh** [comment]
就。。直接女装阿

**Comment by lilydjwg** [comment]
女的怎么了？女的就不能女装了么？ :smile:

**Comment by gitors** [comment]
你可以学我，背心大裤衩啊

**Comment by LxRuzx** [comment]
男装

**Comment by BlahDuckling747** [comment]
学编程的女的，**一般**穿得不会跟正式的女装一样吧
~~（我不了解不要打我）~~

**Comment by liunima1129** [comment]
> 学编程的女的，**一般**穿得不会跟正式的女装一样吧
> ~（我不了解不要打我）~

什么是正式的女装？就裙子吗 不是很爱穿裙子...平时都是穿牛仔裤/leggings偏多 现在夏天也穿穿短裤啥的

**Comment by liunima1129** [comment]
> 你可以学我，背心大裤衩啊

我现在去实习就已经是T恤+篮球裤衩了
一身男装舒适度满分 嘻嘻

**Comment by jshensh** [comment]
这里 T 恤 + 裙子

--------------原始邮件--------------
发件人："gismanli "<notifications@github.com>;
发送时间：2019年7月31日(星期三) 晚上11:47
收件人："komeiji-satori/Dress" <Dress@noreply.github.com>;
抄送："403 Forbidden "<admin@imjs.work>;"Comment "<comment@noreply.github.com>;
主题：Re: [komeiji-satori/Dress] 完了 学编程必须要女装 但是我是女的咋办 (#560)
-----------------------------------

  
你可以学我，背心大裤衩啊
  
我现在去实习就已经是T恤+篮球裤衩了
 一身男装舒适度满分 嘻嘻

**Comment by wyf1996** [comment]
那就，男装⊙∀⊙！

**Comment by hoodlum1980** [comment]
我啥时候 fo 了这个项目，我晕死！

**Comment by hwpi** [comment]
_大不了你男装_

**Comment by madobet** [comment]
这是一个好问题（迫真困惑

**Comment by modibiao** [comment]
好问题哈哈

**Comment by 3088482189** [comment]
说白了就是得穿可爱的衣服？
