### ISSUE TITLE
关于演示页面

### ISSUE THREAD

**Issue by AnonAlpha** [komeiji-satori/Dress#603]
https://drsrel.github.io/

http://satori.mycard.moe/
有谁知道这两个在线演示页面用的是什么程序或是脚本生成的呢？我需要生成一下演示界面

**Comment by papadave66** [comment]
> https://drsrel.github.io/
> 
> http://satori.mycard.moe/
> 有谁知道这两个在线演示页面用的是什么程序或是脚本生成的呢？我需要生成一下演示界面

切换到本项目的web分支，你就可以看到web端代吗了

**Comment by AnonAlpha** [comment]
我看到了，但不清楚是用什么脚本或程序生成的web端代码😂

**Comment by ShirasawaSama** [comment]
使用了 [TravisCI](https://www.travis-ci.org/)

本项目中具体使用位置: [.travis.yml](https://github.com/komeiji-satori/Dress/blob/master/.travis.yml) [deploy](https://github.com/komeiji-satori/Dress/tree/web/deploy)

**Comment by AnonAlpha** [comment]
谢谢🙏😁
