### ISSUE TITLE
为什么这么多start

### ISSUE THREAD

**Issue by mrg123** [komeiji-satori/Dress#609]
你们是什么样的目的?

**Comment by studentmain** [comment]
一般来说，开源软件的目的是造福群众，star只是其目的达成得如何的一种体现

**Comment by xmymsd** [comment]
我是从个人主页中看到这个的，发现超多女装，而且近12K的star。。。。

难道程序员真的这么饥渴吗？

一位已结婚程序员路过。。。

**Comment by a-wing** [comment]
> 一位已结婚程序员路过。。。

您男朋友可爱否（逃
