### ISSUE TITLE
request for rebase

### ISSUE THREAD

**Issue by papadave66** [komeiji-satori/Dress#613]
在commit 2d17c5c 中，我的几张照片超过了1Mib 的要求，所以在commit 651c847 中 压缩了这几张图。不过在在线图片库里，貌似是展示了每一次的commit 所以造成了展示重复。麻烦帮忙重新整合一下那几次的commit，十分感谢

**Comment by oO0oO0oO0o0o00** [comment]
那就是该图库的问题QAQ，Git这边的操作是没问题的，最好是建议图库主人相应改进
