### ISSUE TITLE
ahhh~ so cool nor right ? but I can't do it like you . . .

### ISSUE THREAD

**Issue by YUbuntu0109** [komeiji-satori/Dress#629]
😂 *Suit-dress Mogul ! I want to know why you like to wear women's clothes ?*

**Comment by oO0oO0oO0o0o00** [comment]
你其实 嗯 也可以试试的 会发现挺好玩的呢。

p.s. 你的Java学习笔记不错，谢谢了喵~

**Comment by YUbuntu0109** [comment]
啊哈~ 顿时觉得自己还挺美~

黄宇辉

________________________________
