### ISSUE TITLE
403_Forbidden 这位在男生女装女生男装项目里都有   性别成谜

### ISSUE THREAD

**Issue by Takicheng** [komeiji-satori/Dress#635]

**Comment by JuWell** [comment]
还有女生男装的项目的？？飞机票在哪？

**Comment by Takicheng** [comment]
> 还有女生男装的项目的？？飞机票在哪？

https://github.com/greenaway07/GirlDress

**Comment by wbl381** [comment]
雄兔眼扑朔 雌兔眼迷离 安能辨他是雌雄?

**Comment by misss85246** [comment]
女装大佬的最高境界,让你分不清我到底是女扮男装还是男扮女装!!!!!

**Comment by jshensh** [comment]
这个 repo 不是男扮女装啦。。明明是不限性别的 @Takicheng

**Comment by misss85246** [comment]
@jshensh 上班时间华水摸鱼🧐

**Comment by jshensh** [comment]
@misss85246 这都快要十二点了。。

**Comment by Takicheng** [comment]
> 这个 repo 不是男扮女装啦。。明明是不限性别的 @Takicheng

不好意思  看到女装就先入为主是男生女装了   那请问你是...男孩子女孩子

**Comment by Takicheng** [comment]
@jshensh 不好意思  看到女装就以为是男生女装   不过对你的性别真的好奇( •̀ ω •́ )y

**Comment by jshensh** [comment]
@Takicheng 你在隔壁也发了个 issue 吧，那边一言不合就给删了，那可真是很棒棒呢。。
我也没啥好说的，发个以前在医院抽血拍的图吧。。
![https://raw.githubusercontent.com/jshensh/jshensh.github.io/master/uploads/2019/10/IMG_20190815_083220.jpg](https://raw.githubusercontent.com/jshensh/jshensh.github.io/master/uploads/2019/10/IMG_20190815_083220.jpg)

**Comment by lilydjwg** [comment]
This is why I don't participate: it creates misunderstanding.

**Comment by madobet** [comment]
> This is why I don't participate: it creates misunderstanding.

这只狐狸的头像好眼熟，你是在 arch linux 中文论坛里活跃的那个大佬吗

**Comment by lilydjwg** [comment]
On Fri, Dec 20, 2019 at 04:53:12AM -0800, Tooko Madobe wrote:
> 
> 这只狐狸的头像好眼熟，你是在 arch linux 中文论坛里活跃的那个大佬吗

嗯，是我。并不是大佬。

-- 
Best regards,
lilydjwg

**Comment by 42SL** [comment]
有着不同于一般人的灵活性别
