### ISSUE TITLE
What the heck is this? 

### ISSUE THREAD

**Issue by coutHan** [komeiji-satori/Dress#651]
Why do Chinese people like to post some irrelevant stuff on Github? This is really disappointing.

**Comment by nikoqw** [comment]
Infact, this is a project that encourage more people to learn and understand, to know the ideology of github。There's a tutorial that teach quasi-programmer and non-programmer (but who collaborate to create projects)  to use github. So them used a example (to teach): upload your picture. Just like what you do on some other software and platform. So this aroused a lot of interest. They start to learn and know the way of github: branch, pull requests, merge, fork. For example: to add a feauture u need to fork and operate the branch, pull req of bad "code" will not be accepted, and so on.
