### ISSUE TITLE
添加英文說明

### ISSUE THREAD

**Issue by nikoqw** [komeiji-satori/Dress#659]
## 玄談
https://github.com/komeiji-satori/Dress/issues/651
https://github.com/komeiji-satori/Dress/issues/658
因文化差異、且本項目沒有**針對外國人詳細的英語簡介**，故很多外國人看到這「都是圖片」的github倉庫會感到很詫異。不知道此項目的用意，也會擔心這會不會爲github帶來不好的影響。

如今本項目過大（名聲）、給本是主要爲開源程序服務的github  以及爲了參加開源程序開發的用戶帶來不必要的信息等等（這也是反對者以及不知情的外國人的反對原因之一），一定程度上給此項目帶來了困難。

## 此提議（撰寫說明）之主要目的：
- 避免誤會。從某方面來看，此項目**很可能在一定時期之內成爲遭受眾人反對/厭惡的對象**。
- 着重本質。使大家不要忘記項目的所爲。

**Comment by nikoqw** [comment]
Implemented myself

**Comment by b00sher** [comment]
Thanks for what you've done!
I'm just wondering, since I found [another repo](https://github.com/greenaway07/GirlDress) (also on Chinese) like this, is it a local meme or some kind of strike against Microsoft/whatever? Not like I'm doubting that posting photos of yourself is the best way to learn.

**Comment by b00sher** [comment]
Thanks for what you've done!
I'm just wondering, since I found [another repo](https://github.com/greenaway07/GirlDress) like this (also on Chinese), is it a local meme or some kind of strike against Microsoft/whatever? Not like I'm doubting that posting photos of yourself is the best way to learn.

**Comment by nikoqw** [comment]
Haha, yes it's not the best way to learn how to use git. Their objective is that 
1. to let the ***average person*** simply know about the idea of github, like the branch, and encourage them try to create pull request, simply use github. So them used a simple example like posting the photo. This is familiar to them because they do the same thing on lot of others platform.
2. create something new(diffierent?) on github.

**Comment by nikoqw** [comment]
I'm first seen that repo u showed me. I really don't know that.

**Comment by b00sher** [comment]
> it's not the best way to learn how to use git

isn't it? One small step for human, one big step for open source. This is definitely a conspiracy against Microsoft, I can sense it. 

Our future depends on us. We must not let Microsoft buy StackOverflow. I will create open an issue to ask for permission to claim this repository as a basement of international (mostly Chinese) conspiracy against Microsoft. And for those who think it is a joke and we can't bring communism into open source, think again.
