### ISSUE TITLE
关于英文的使用

### ISSUE THREAD

**Issue by gaoyaoxin** [komeiji-satori/Dress#689]
我大致浏览了一下 [READM DETAIL](https://github.com/komeiji-satori/Dress/blob/master/README_DETAIL.md)，发现一些基本的语法是有问题的，比如`them are`（主语用了宾格），`The contributor are`（主谓不一致），`can (and already) aroused`（情态动词后面没接动词原形），`This project also develop`（主谓不一致）；另外遣词造句上可能也没那么通顺，例如`ideology`一词可能政治含义比较浓。
因此，不知 repo 的主要维护者是否能提供先一个比较好的中文版本，再以此为基准翻译为英文（我可以提供帮助）。直接拿现有英文的进行改动，小改只能把语法错误消除了，大改则可能把某些意思没有表达清楚。

**Comment by nikoqw** [comment]
傻乎乎把寫好的中文版本寫到一文件裏頭又創建了pull requests。沒想到直接把中文版本給你回覆就行了
原文 #690

**Comment by gaoyaoxin** [comment]
谢谢，详见 #692.

**Comment by infnan** [comment]
#675 也在做相同事情😂

**Comment by PoiDaisuki** [comment]
嗯...贴到grammarly里看了眼：（(删除)[添加]，另有10个次要问题←大概就是指的用词不当，所有建议github→GitHub已忽略）
Of course, (them)[they] are......
without[ the] contribution of code
the size of[ a] repo cannot...
The contributor[s] are asked...
In[ the] future, we...
This project also develop[s] their team cooperation ability...
join the discussion and solve[ a] problem such as...
另外is this project really helpful 第二段的时态我没搞懂...可能是我太菜了？
还有就是在readme里用缩写（比如那个ctrl）有些不正规吧...
//倒数第二个repo（how to ctrl the size of repo）个人感觉repo前缺一个冠词，但是他没提示←没提示的错误多了去了

**Comment by gaoyaoxin** [comment]
> 嗯...贴到grammarly里看了眼：（(删除)[添加]，另有10个次要问题←大概就是指的用词不当，所有建议github→GitHub已忽略）
> Of course, (them)[they] are......
> without[ the] contribution of code
> the size of[ a] repo cannot...
> The contributor[s] are asked...
> In[ the] future, we...
> This project also develop[s] their team cooperation ability...
> join the discussion and solve[ a] problem such as...
> 另外is this project really helpful 第二段的时态我没搞懂...可能是我太菜了？
> 还有就是在readme里用缩写（比如那个ctrl）有些不正规吧...
> //倒数第二个repo（how to ctrl the size of repo）个人感觉repo前缺一个冠词，但是他没提示←没提示的错误多了去了

# 我在#692 改写了一下英文版的。
