### ISSUE TITLE
我人没了

### ISSUE THREAD

**Issue by Co2333** [komeiji-satori/Dress#740]
![124C06DD-68A8-47E3-BB6D-D2B55E7A9493](https://user-images.githubusercontent.com/25259084/68990030-273be580-0889-11ea-9340-dd7d57cdb5ca.jpeg)

你能想像你的awesome照在北极保存1000年么

**Comment by m2kar** [comment]
哈哈哈，赶紧把照片压缩成100kb以内的大小，不然人家不收录了

**Comment by Co2333** [comment]
牛逼。。。
