### ISSUE TITLE
因为国内网络原因,搬运到了自己的gitee上,欢迎围观

### ISSUE THREAD

**Issue by Violet-VE** [komeiji-satori/Dress#831]
https://gitee.com/violetve/Dress
因为对gitee和github的同步操作不熟,可能不同步,也可能会删库重建

**Comment by Salted-Fish-Swimming** [comment]
404，挂了。

**Comment by xujunwei-hp** [comment]
404 T_T

**Comment by Violet-VE** [comment]
已经有国内地址了，我的删了。。。
https://gitee.com/zy143l/Dress
