### ISSUE TITLE
一个问题【女】

### ISSUE THREAD

**Issue by luyouyeah** [komeiji-satori/Dress#844]
女生可以一起玩吗？(*^▽^*)

**Comment by bangbang93** [comment]
可以啊

**Comment by LainSakura** [comment]
羡慕女孩子QAQ

**Comment by luyouyeah** [comment]
前几天是不是github跪了

**Comment by jshensh** [comment]
可以阿，看 [CONTRIBUTING.md](https://github.com/komeiji-satori/Dress/blob/master/CONTRIBUTING.md)
