### ISSUE TITLE
warning: Clone succeeded, but checkout failed.在客户端要怎么做

### ISSUE THREAD

**Issue by mickeywaley** [komeiji-satori/Dress#848]
Resolving deltas: 100% (2094/2094), done.
error: invalid path '0xVssblt/第一次. 好羞涩啊(つ﹏⊂)/不好看不要骂我{{{(>_<)}}}.md'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
能不能把这个路径名称改下啊？
克隆成功，签出失败。

**Comment by jshensh** [comment]
😂😂😂 @Vssblt

**Comment by bangbang93** [comment]
fixed in #849
