### ISSUE TITLE
图片不见了

### ISSUE THREAD

**Issue by moustache-lady** [komeiji-satori/Dress#858]
刚注册的账号，上传了两张图片，却找不到了，第一次玩Git，谁能告诉我一下图片在哪？标题是：胡子姐来了，谢谢！

**Comment by bangbang93** [comment]
https://github.com/komeiji-satori/Dress/commit/6280e8359ba03f2517cb90da6a3b79a77eb0dc94
你怎么上传的

**Comment by moustache-lady** [comment]
先点create new file按钮，然后点Upload file 按钮
