### ISSUE TITLE
8Mi-VtbNews 2020-04-16

### ISSUE THREAD

**Issue by 8MiYile** [komeiji-satori/Dress#860]
https://github.com/8MiYile/HomoCraftServer/blob/master/lib/8Mi_VtbNews/2020-04-16.md<br>
对于这种事,女装dalao们泥萌咋看???

**Comment by studentmain** [comment]
git clone到本地用vscode看

**Comment by 8MiYile** [comment]
@studentmain 不愧是你

**Comment by studentmain** [comment]
挂人好，但是在无关的github项目里面挂人不好。我们的每一句话都会发给watch了这个项目的几百个人。
