### ISSUE TITLE
照片里是男的还是女的？

### ISSUE THREAD

**Issue by fangyulovechina** [komeiji-satori/Dress#861]

**Comment by moustache-lady** [comment]
都是男的

**Comment by LainSakura** [comment]
女孩子也可以啊OvO http://alturl.com/mzjdt

**Comment by jshensh** [comment]
不用纠结这个问题，[CONTRIBUTING.md](https://github.com/komeiji-satori/Dress/blob/master/CONTRIBUTING.md) 写明了不限性别，可爱就好

**Comment by Potato-Yao** [comment]
GitHub上怎么会有女孩子（doge
