### ISSUE TITLE
想知道怎么判断性别

### ISSUE THREAD

**Issue by SolomonLeon** [komeiji-satori/Dress#862]
大佬们都好美
认不出了~(*´∀｀)

**Comment by moustache-lady** [comment]
我快手号里面有识别女装大佬的视频，有兴趣可以去看看

**Comment by jshensh** [comment]
@moustache-lady 我觉得甩你一打混着女孩子的照片让你看的话，成功率应该不超过 60%

**Comment by moustache-lady** [comment]
> @moustache-lady 我觉得甩你一打混着女孩子的照片让你看的话，成功率应该不超过 60%

看照片肯定是有难度，我视频里面说的是在街上看到美女如何判断

**Comment by jshensh** [comment]
@moustache-lady 阿你开心就好

**Comment by lilydjwg** [comment]
1. 检查染色体
2. 检查身份证
3. 询问对方
4. 机器学习

**Comment by SolomonLeon** [comment]
@lilydjwg 询问的话问不出口唉~
机器学习可以做到吗？我感觉女装大佬和女生之间的性别特征差异越来越小了……

**Comment by lilydjwg** [comment]
On Fri, Apr 17, 2020 at 01:54:17AM -0700, Solomon Leon wrote:
> @lilydjwg 询问的话问不出口唉~
> 机器学习可以做到吗？我感觉女装大佬和女生之间的性别特征差异越来越小了……

你理解有偏差。以上四个方案得出的是四个不同的结果。波普尔的三个世界听说过
吗？大致上就对应那三个世界，外加一个AI的世界。

-- 
Best regards,
lilydjwg

**Comment by SolomonLeon** [comment]
@lilydjwg 听说过，明白了，谢谢~

**Comment by sjw111** [comment]
安能辨我是雄雌

**Comment by Co2333** [comment]
安能辨我是雄

**Comment by Potato-Yao** [comment]
没必要判别，因为GitHub全是男的（doge

**Comment by jshensh** [comment]
> 没必要判别，因为GitHub全是男的（doge

您是不是在找 "GayHub"

**Comment by num-arrver** [comment]
GayHub可太草
我记得Git上好像有关于这一类机器学习的项目(据作者说成功率高达百分之91)

**Comment by BBleae** [comment]
I don't think gender matters.

**Comment by MengFanjun020906** [comment]
来这个项目了，就没必要分辨性别了

**Comment by num-arrver** [comment]
不不不，在你来Git的这一刻起性别就不重要了
