### ISSUE TITLE
如何理解本项目采用的CC-BY-NC-SA协议？

### ISSUE THREAD

**Issue by RuikangSun** [komeiji-satori/Dress#871]
比如说，我想向他人介绍本项目，需要引用大佬的女装照，是不是需要把整个项目所有的女装文件一同附带？感觉这样不现实呀。

**Comment by RuikangSun** [comment]
这个“禁止演绎”，是指开发者（doge.jpg）必须让引用的部分图片（比如引用一两张）完整，还是必须把项目中所有的图片全部引用才行？

**Comment by zzkklep** [comment]
？小伙子你有问题

**Comment by RuikangSun** [comment]
> 
> 
> ？小伙子你有问题

嘤嘤嘤我不是，我没有，别乱说

**Comment by zzkklep** [comment]
> 
> 
> > ？小伙子你有问题
> 
> 嘤嘤嘤我不是，我没有，别乱说
禁止演绎是不许你P图，不是不许你传播

**Comment by RuikangSun** [comment]
> 
> 
> > > ？小伙子你有问题
> > 
> > 
> > 嘤嘤嘤我不是，我没有，别乱说
> 
> 禁止演绎是不许你P图，不是不许你传播

禁止演绎能不能将整个项目拆散传播呢。。。就是发个别的女装照23333

**Comment by zzkklep** [comment]
> > > > ？小伙子你有问题
> > > 
> > > 
> > > 嘤嘤嘤我不是，我没有，别乱说
> > 
> > 
> > 禁止演绎是不许你P图，不是不许你传播
> 
> 禁止演绎能不能将整个项目拆散传播呢。。。就是发个别的女装照23333

反正就，你不P图就OK，拆散可以，我是这么理解的

**Comment by qwq233** [comment]
理解CC BY-NC-SA要这么理解
BY标注原作者
NC禁止商业用途
这俩好理解
SA相同方式传播 这里的相同方式其实是强制相同的许可证即CC BY-NC-SA，你必须使用它或与之兼容的许可证
```
1. 您适用的“演绎作者的许可”协议必须是与本许可协议具有相同授权要素的知识共享(Creative Commons)许可协议（可以是本版本或后续版本），或者其他与“署名－非商业性使用－相同方式共享”协议兼容的许可协议。
2. 您必须提供您适用的“演绎作者的许可”协议全文或者该许可协议的网址(URI)或超链接。依据您分享您的演绎作品(Adapted Material)所使用的媒介、方法及情況，您可以采用任何合理方式满足此条件。
3. 您不得提出或施加任何附加或不同的条款或条件、或在演绎作品(Adapted Material)上应用任何有效的技术措施，以限制使用者行使依您所适用的“演绎作者的许可”协议所授予的权利。
```

**Comment by RuikangSun** [comment]
Close old issues.
