### ISSUE TITLE
凑个热闹

### ISSUE THREAD

**Issue by CheukFaiho** [komeiji-satori/Dress#91]
真实长发+日常女装上班的人表示一点压力都没有→_→

**Comment by MikaGuraNTK** [comment]
羡慕死了 ←_←

**Comment by CheukFaiho** [comment]
> Talk is cheap. Show me the pull request.

https://github.com/CheukFaiho/Dress/tree/master/打酱油...
头像也算吧hhh

**Comment by CheukFaiho** [comment]
> Talk is cheap. Show me the pull request.

https://github.com/CheukFaiho/Dress/tree/master/打酱油.../
头像也算吧 hhhhh

**Comment by zh99998** [comment]
> > Talk is cheap. Show me the pull request.
> 
> [https://github.com/CheukFaiho/Dress/tree/master/打酱油.../](https://github.com/CheukFaiho/Dress/tree/master/%E6%89%93%E9%85%B1%E6%B2%B9.../)
> 头像也算吧 hhhhh

你倒是发pr
