### ISSUE TITLE
为啥这个女装的项目star上千，百思不得姐

### ISSUE THREAD

**Issue by hasone** [komeiji-satori/Dress#92]
卧槽，这样把代码pull进来，是不是比那些花钱造假的高尚多了

**Comment by muzea** [comment]
这个项目比较实用 🐶

**Comment by Luoyingliang** [comment]
还有个repo里面只有注释，也是分分钟star破冰。总结一点就是，在gayhub里面，受欢迎的repo要么非常hardcore，要么非常咸鱼。

认真敲代码是不可能的

**Comment by yukiexe** [comment]
導流 -> #82
