### ISSUE TITLE
【github小白，瑟瑟发抖，200斤肥宅的女装你想看吗？】

### ISSUE THREAD

**Issue by Observer73** [komeiji-satori/Dress#951]
这个项目不错，但是对于肥宅太不友好了，我女票说不借我她的小裙子，怕我撑坏了，嘤嘤嘤，怎么办？

**Comment by 100725** [comment]
硬抢

**Comment by lssp-maker** [comment]
趁她睡着了

**Comment by rurico** [comment]
> 这个项目不错，但是对于肥宅太不友好了，我女票说不借我她的小裙子，怕我撑坏了，嘤嘤嘤，怎么办？
@Observer73 自己买吧。

**Comment by kawashiro-ryofu** [comment]
不敢想象……

**Comment by nidbCN** [comment]
买XXXL/XXL或许是可以塞进去的（确信

XL以下的话，上衣没准，裙子是塞不进去的

但是你女朋友我觉得不会是穿XXXL的，所以不借给你也正常

等等为什么你有女朋友呜呜呜

**Comment by ZhangJianBeiJing** [comment]
牛批。。。

**Comment by itqihou** [comment]
I see you all use the avatars of beautiful girls in two dimensions. Are you all European and American?

**Comment by nidbCN** [comment]
> 

Most of us are Chinese....

**Comment by nidbCN** [comment]
> I see you all use the avatars of beautiful girls in two dimensions. Are you all European and American?

Most of us are Chinese
