### ISSUE TITLE
github 博客首页加载性能问题

### ISSUE THREAD

**Issue by Michael18811380328** [komeiji-satori/Dress#971]
<img width="530" alt="屏幕快照 2020-10-30 18 33 30" src="https://user-images.githubusercontent.com/37589122/97695111-7b61c900-1ade-11eb-9f89-a5052515cf88.png">

https://drsrel.github.io/albums
首页加载时，渲染 235个 用户（DIV节点），这样造成了界面卡顿。
首页能否优化成图片 lazy-loading?

**Comment by chloe-lam** [comment]
我有个PR加了，坐等大佬Merge

**Comment by Michael18811380328** [comment]
> 我有个PR加了，坐等大佬Merge

好的，感谢。我主要写 React 和 VUE，ang 不是太熟悉，所以感谢大佬~~~

**Comment by chloe-lam** [comment]
@Michael18811380328  我ng很66，日往我可以改个好看的theme， 不过看travis卡住了 bash build,项目可以试下用webapck压压图片，刚好webpack出了新玩法，去压一压master 和check一下image path, 有些是empty string.

**Comment by Michael18811380328** [comment]
现在界面加载已经很顺畅了，感谢 ng 大佬！
