### ISSUE TITLE
怎么能有这么无耻的库

### ISSUE THREAD

**Issue by harvey-woo** [komeiji-satori/Dress#98]
太过分了，万一女装大佬把我掰弯了怎么办

**Comment by WOSHINPC** [comment]
> 太过分了，万一女装大佬把我掰弯了怎么办

只要你也成为女装大佬就不会被掰弯了啊~

**Comment by Luoyingliang** [comment]
> > 太过分了，万一女装大佬把我掰弯了怎么办
> 
> 只要你也成为女装大佬就不会被掰弯了啊~

正确回答是，你把他也掰弯就可以结婚了

**Comment by harry-gzcn** [comment]
> > > 太过分了，万一女装大佬把我掰弯了怎么办
> > 
> > 
> > 只要你也成为女装大佬就不会被掰弯了啊~
> 
> 正确回答是，你把他也掰弯就可以结婚了

虽然本可以搞基，但是玩成了百合也问题不大啊

**Comment by Luoyingliang** [comment]
> > > > 太过分了，万一女装大佬把我掰弯了怎么办
> > > 
> > > 
> > > 只要你也成为女装大佬就不会被掰弯了啊~
> > 
> > 
> > 正确回答是，你把他也掰弯就可以结婚了
> 
> 虽然本可以搞基，但是玩成了百合也问题不大啊

百合，，，嘿嘿嘿（痴汉脸
是不是repo里面缺点百合合照

**Comment by harvey-woo** [comment]
> > > > > 太过分了，万一女装大佬把我掰弯了怎么办
> > > > 
> > > > 
> > > > 只要你也成为女装大佬就不会被掰弯了啊~
> > > 
> > > 
> > > 正确回答是，你把他也掰弯就可以结婚了
> > 
> > 
> > 虽然本可以搞基，但是玩成了百合也问题不大啊
> 
> 百合，，，嘿嘿嘿（痴汉脸
> 是不是repo里面缺点百合合照

大片的感觉

**Comment by Luoyingliang** [comment]
这个repo可以改名叫做一键女装了

**Comment by Luoyingliang** [comment]
> > > > > > 太过分了，万一女装大佬把我掰弯了怎么办
> > > > > 
> > > > > 
> > > > > 只要你也成为女装大佬就不会被掰弯了啊~
> > > > 
> > > > 
> > > > 正确回答是，你把他也掰弯就可以结婚了
> > > 
> > > 
> > > 虽然本可以搞基，但是玩成了百合也问题不大啊
> > 
> > 
> > 百合，，，嘿嘿嘿（痴汉脸
> > 是不是repo里面缺点百合合照
> 
> 大片的感觉

这个repo可以改名叫做一键女装了
