### ISSUE TITLE
有深度学习女装群吗？

### ISSUE THREAD

**Issue by yhqjohn** [komeiji-satori/Dress#982]
非常向往知乎上他们说的技术和女装之间反复歪的群，不知道有没有同时对炼丹和女装都感兴趣的同好，有没有这样的群。
一边欣赏小姐姐，一边提高自己的女装技术，一边看技术大佬吹b增长见闻，岂不美哉？

**Comment by Michael18811380328** [comment]
自己搭梯子去找吧

**Comment by SinKy-Yan** [comment]
同问，找到了叫我🥳

**Comment by Thomasvader** [comment]
可以直接创建一个群！！！

**Comment by RubyKiss** [comment]
因为内心是女的外表是难的所以很想要变得好看！对吧。
